name: PR

on: pull_request

jobs:
  build-lint-test:
    # Prevents changesets action from creating a PR on forks
    if: github.repository == 'calebdwilliams/element-internals-polyfill'
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node 16.x
        uses: actions/setup-node@main
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm i

      - name: Build packages
        run: npm run build

      - name: Test
        run: npm test
